### ISSUE TITLE
Return suggested filename column from clean

### ISSUE THREAD

**Issue by dhope** [dhope/ARUtools#3]
Our files are uploaded to the Wildtrax system and they have a particular required filename format (SiteID_Date_Time.wav). 

Previously I had used the columns `yyyymmdd` & `hhmmss` to generate these names using the code:
`WildTraxName = glue::glue("{location}_{yyyymmdd}_{hhmmss}")`, but I've noticed with the updated `clean_metadata` those character strings of date and time are dropped, so I'm recreating them from the filenames.

However, since you're already extracting those in `clean_metadata` it might be worth just creating another column with date_time_chr or output_filename that includes the `site_id` also.

The alternative is to keep those `yyyymmdd` & `hhmmss` columns, but as I think the only use case right now is create the output filename, just doing that directly might be more succinct. 

Happy to discuss.

**Comment by dhope** [comment]
Sorry, yeah I wasn't clear about use case. Essentially I need the WildTraxName in the metadata so I can link my metadata back to the data downloaded from wildtrax once the interpretations are complete.

What you describe exists in a couple of the 'non-essential' functions (https://github.com/dhope/ARUtools/blob/main/R/Clip_wav_file.R), which uses the WildTraxName column to create the new file name.

So yeah, it could a helper function that repeats what you do internally with this code ( https://github.com/dhope/ARUtools/blob/647052102fb155e5fca7e7941fe58b5913ec59bd/R/clean_metadata.R#L175-L180). My initial thought was it would just be easier to return the filename directly in `clean_metadata`, but perhaps it reduces the generalization of the function if it is returning a column for one specific use case.

Perhaps the best use is then is to take the generated date_times and use a  `gen_date_time_chr ` helper function that returns date_time in `yyyymmdd_hhmmss` format for a given vector or single set of date_times.

something like 
```
gen_date_time_chr <- function(date_times, date_time_sep) {
  yyyy <- lubridate::year(date_times)
  mm <- lubridate::month(date_times) |> 
    stringr::str_pad( width = 2, side = 'left', pad = "0")
  dd <- lubridate::day(date_times) |> 
    stringr::str_pad( width = 2, side = 'left', pad = "0")
  hh <- lubridate::hour(date_times) |> 
    stringr::str_pad( width = 2, side = 'left', pad = "0")
  min_mm <- lubridate::minute(date_times) |> 
    stringr::str_pad( width = 2, side = 'left', pad = "0")
  ss <- lubridate::second(date_times) |> 
    stringr::str_pad( width = 2, side = 'left', pad = "0")
  
  glue::glue("{yyyy}{mm}{dd}{date_time_sep}{hh}{min_mm}{ss}")
}
```
I can then create my filenames with: 
```mutate(m, WildTraxName = glue::glue("{site_id}_{gen_date_time_chr(date_time, '_')}"))```
```
This doesn't seem to be slow and then doesn't add more stuff into `clean_metadata` that won't always be used. What do you think?

**Comment by steffilazerte** [comment]
Perhaps one step farther, a `add_wildtrax()` function that combines the two steps? So it's only added if someone specifically wants it added?

**Comment by steffilazerte** [comment]
I added this function which uses R's `format()` to grab the YYYYMMDD_HHSSMM from the `date_time` column

```
> m <- clean_metadata(project_files = example_files)
Extracting ARU info...
Extracting Dates and Times...
> m <- add_wildtrax(m)
> m
# A tibble: 42 × 9
   file_name                     type  path                                             aru_type  aru_id     site_id date_time           date       wildtrax_file_name   
   <chr>                         <chr> <chr>                                            <chr>     <chr>      <chr>   <dttm>              <date>     <glue>               
 1 P01_1_20200502T050000_ARU.wav wav   a_BARLT10962_P01_1/P01_1_20200502T050000_ARU.wav BarLT     BARLT10962 P01_1   2020-05-02 05:00:00 2020-05-02 P01_1_20200502_050000
 2 P01_1_20200503T052000_ARU.wav wav   a_BARLT10962_P01_1/P01_1_20200503T052000_ARU.wav BarLT     BARLT10962 P01_1   2020-05-03 05:20:00 2020-05-03 P01_1_20200503_052000
 3 P03_1_20200506T100000_ARU.wav wav   a_BARLT10962_P03_1/P03_1_20200506T100000_ARU.wav BarLT     BARLT10962 P03_1   2020-05-06 10:00:00 2020-05-06 P03_1_20200506_100000
 4 P05_1_20200507T050000_ARU.wav wav   a_BARLT10962_P05_1/P05_1_20200507T050000_ARU.wav BarLT     BARLT10962 P05_1   2020-05-07 05:00:00 2020-05-07 P05_1_20200507_050000
 5 P06_1_20200509T052000_ARU.wav wav   a_BARLT10962_P06_1/P06_1_20200509T052000_ARU.wav BarLT     BARLT10962 P06_1   2020-05-09 05:20:00 2020-05-09 P06_1_20200509_052000
 6 P08_1_20200511T100000_ARU.wav wav   a_BARLT10962_P08_1/P08_1_20200511T100000_ARU.wav BarLT     BARLT10962 P08_1   2020-05-11 10:00:00 2020-05-11 P08_1_20200511_100000
 7 P04_1_20200506T050000_ARU.wav wav   a_BARLT11111_P04_1/P04_1_20200506T050000_ARU.wav BarLT     BARLT11111 P04_1   2020-05-06 05:00:00 2020-05-06 P04_1_20200506_050000
 8 P04_1_20200507T032500_ARU.wav wav   a_BARLT11111_P04_1/P04_1_20200507T032500_ARU.wav BarLT     BARLT11111 P04_1   2020-05-07 03:25:00 2020-05-07 P04_1_20200507_032500
 9 P02_1_20200504T052500_ARU.wav wav   a_S4A01234_P02_1/P02_1_20200504T052500_ARU.wav   SongMeter S4A01234   P02_1   2020-05-04 05:25:00 2020-05-04 P02_1_20200504_052500
10 P02_1_20200505T073000_ARU.wav wav   a_S4A01234_P02_1/P02_1_20200505T073000_ARU.wav   SongMeter S4A01234   P02_1   2020-05-05 07:30:00 2020-05-05 P02_1_20200505_073000
```

@dhope Does this suit your needs?

**Comment by dhope** [comment]
This is great. Thanks.
