### ISSUE TITLE
Q - Deprecation when changing names?

### ISSUE THREAD

**Issue by steffilazerte** [dhope/ARUtools#7]
Hi @dhope!

I'm starting in on the format_clip_wave functions. As part of the clean up, I'm standardizing the argument names to match those used in the first set of functions.

For example we use `col_aru_id` and `col_site_id` to define the argument which notes the name of a column required. In `format_clip_wave()` there are `sub_dir_out_col` `filepath_in_col` etc. I'd like to rename them to `col_subdir_out` and `col_filepath_in` etc. 

Do you want me to put in formal deprecations/defunct messages, or do we assume that this is a big enough set of changes for a small enough set of people that we can just brute force it through?

**Comment by dhope** [comment]
No need for warnings. Not enough users yet to worry about messages.
